SUPABASE_URL = "https://gakmklpspjliazhkeppr.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdha21rbHBzcGpsaWF6aGtlcHByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDcyMjY5NDIsImV4cCI6MjAyMjgwMjk0Mn0.6-EdNXi9pXSMZm6Nmr-Aze8HjvGfT9TxyHNFOmLwYb8"
SMTP_PASSWORD = "jbxu aqkp jzba cdze"